### PR TITLE
Update TOD rule

### PR DESCRIPTION
**Pull request by d-wasserman**
Pull Request to Branch of Complete Street Rule for TOD Update. 

Comment by @lexieleileiduan 
> I'm not sure whether the Initial_Bus/Rail_FAR_Bonus was calculated the right way. Can you verify that? It would be a quick fix if we need to change anything.
> 
> The forms seem quite similar, do we need other criteria?

### CODE REVIEW

**Comment by d-wasserman** [comment]
@lexieleileiduan 

Can you clean up the the inspector? I see duplicate transit variable types, but I am not sure which one works. 
When I edit both of them, I did not see any changes. Any suggestions on things to try on a test polygon?

**Comment by lexieleileiduan** [comment]
which ones?

**Comment by lexieleileiduan** [comment]
Ahh I see.. I forgot you created some decay and increment variables already.. I did not use them but created new ones. Yep change the TOD settings to change the height. The control of TOD is only about height at this point. There is a group "temporary", that contains two variables that I think we will need in the parcel data, for now they are placeholders for the actual values. the Z_FAR is the existing FAR based on zoning. We then calculate bonus FAR. Total bonus far = bus bonus far + rail bonus far. The final FAR used to generated building is the sum of both. Bus/rail bonus FAR is calculated with the _get_Bonus FAR function (probably not the exact name? but it's the last function in the rule). If you change the increment or decay in the TOD settings height will change.

**Comment by lexieleileiduan** [comment]
I will clean up the inspector tonight. Can you also check the attribute settings in the TOD? especially the two with case scenarios. I wanna make sure they are what you were talking about. Do we need more control over form changes? more than just height? how detailed?

**Comment by d-wasserman** [comment]
I will start checking the attributes for the TOD settings. I did not get them to change much of the building behavior, so maybe checking that would be good to do before. I might have missed something though, so I will check this weekend. 

Just height might be good for now, we can talk about next steps in the presentation for more functionality based on feedback.

**Pull request merged**
